config/routes.rb
Sword::Engine.routes.draw do
  resources :deposit
  resources :servicedocument
end

app/models/sword/application_record.rb
module Sword
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/sword/mets.rb
module Sword
  class Mets
    include ActiveModel::Model

    attr_accessor :xml
    attr_reader :metadata
    attr_reader :bitstreams

    def initialize(args)
      @xml = args[:xml]
      @metadata = Hash.new {|h,k| h[k]=[]}
      @bitstreams = Array.new()
      load_metadata
      load_bitstreams
    end

    def load_metadata
      Sword.config.ingest['fields'].each do |field|
        metadata_holder = xml.xpath("#{Sword.config.ingest['xpath_prefix']}#{field[1]['xpath']}",Sword.config.ingest['namespace'])
        metadata_holder.each do |metadata_string|
          metadata[field[0]] << metadata_string.inner_html
        end
      end
    end

    def load_bitstreams
      bitstream_metadata = xml.xpath(Sword.config.ingest['bitstreams']['xpath'],Sword.config.ingest['namespace'])
      bitstream_metadata.each do |bitstream|
        bitstreams << bitstream['xlink:href']
      end
    end
  end
end

app/models/sword/package.rb
module Sword
  class Package
    include ActiveModel::Model

    attr_accessor :filename
    attr_reader :files, :path, :bitstreams, :work

    def initialize(args)
      @filename = args[:filename]
      @bitstreams = Array.new()

      unzip
      mets
      upload_bitstreams
      create_work

    end

    def files
      @files ||= []
    end

    private

    def mets
      @mets ||= Mets.new(xml: Nokogiri::XML(File.open(File.join(@path,'mets.xml'))))
    end

    def unzip

      begin
        @path = initialize_directory(File.join(Sword.config.working_path, File.basename(@filename, ".zip")))

        Zip::File.open(File.join(Sword.config.upload_path,@filename)) do |file_to_extract|
          file_to_extract.each do |compressed_file|
            file_to_extract.extract(compressed_file.name,File.join(path,compressed_file.name))
            files << compressed_file.name
          end
        end
      rescue => error_msg
        Sword.config.logger.error error_msg
      end
    end

    def upload_bitstreams
      mets.bitstreams.each do |bitstream|
        hyrax_file = Hyrax::UploadedFile.create(file: File.open(File.join(path,bitstream)))
        hyrax_file.save
        bitstreams.push(hyrax_file)
      end
    end

    def initialize_directory(dir)
      Dir.mkdir dir unless Dir.exist?(dir)
      return dir
    end

    def create_work
      mets.metadata[:id] = ActiveFedora::Noid::Service.new.mint
      mets.metadata[:visibility] = "open"
      @work = Work.new(mets.metadata)
      work.apply_depositor_metadata("acollier@calstate.edu")
      work.save

      AttachFilesToWorkJob.perform_now(work,bitstreams)
    end

  end
end

app/controllers/sword/application_controller.rb
module Sword
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/sword/deposit_controller.rb
require_dependency "sword/application_controller"

module Sword
  class DepositController < ApplicationController

    skip_before_filter :verify_authenticity_token

    def index
      puts response.headers
    end

    def create
      # render :text => request.headers["Content-disposition"].split('=').last

      # TODO: This response is temporary, the 200 response should only come
      # after the item has been successfully ingested into the IR

      filename = request.headers["Content-disposition"].split('=').last
      unless filename.nil?
        File.open(File.join(Sword.config.upload_path,filename), "wb") do |f|
          f.write(request.raw_post)
        end

        @sword_package = Package.new(filename: filename)

        Sword.config.logger.info "#{@sword_package.filename} successfully uploaded"

        Sword.config.logger.info "Creating item with id: #{@sword_package.work.id}"

        @work = @sword_package.work
        # @work_url = app.hyrax_work_path(@work)

        render "index.xml.erb"
      end
    end
  end
end

app/controllers/sword/servicedocument_controller.rb
require_dependency "sword/application_controller"
require "sword/log"

module Sword
  class ServicedocumentController < ApplicationController

    attr_reader :user

    before_filter :http_authenticate

    # before_action :authenticate_user!

    def index
      admin_sets_for_user
      render "index.xml.erb"
    end

    protected

    def http_authenticate
      authenticate_or_request_with_http_basic do |username, password|
        Sword.config.logger.info "Attempting authentication for: #{username}"
        @user ||= User.find_by_user_key(username)
        !user.nil? && user.valid_password?(password)
      end
      warden.custom_failure! if performed?
    end

    def admin_sets_for_user
      @admin_sets_for_user ||= @user.ability.admin_set_ids_for_deposit
    end

  end
end

app/helpers/sword/application_helper.rb
module Sword
  module ApplicationHelper
  end
end

app/helpers/sword/deposit_helper.rb
module Sword
  module DepositHelper
  end
end

app/helpers/sword/service_document_helper.rb
module Sword
  module ServiceDocumentHelper
  end
end

app/views/layouts/sword/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sword</title>
  <%= stylesheet_link_tag    "sword/application", media: "all" %>
  <%= javascript_include_tag "sword/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sword/deposit/index.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<atom:entry xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sword="http://purl.org/net/sword/">
   <atom:id><%= @work.id %></atom:id>
   <atom:author>
      <atom:name>acollier@calstate.edu</atom:name>
   </atom:author>
   <atom:content type="application/zip" src=""/>
   <atom:link href="" rel="part" type="application/pdf"/>
   <atom:link href="" rel="alternate" type="text/html"/>
   <atom:published></atom:published>
   <atom:rights type="text"></atom:rights>
   <% @work.description.each do |desc| %>
   <atom:summary type="text"><%= desc %></atom:summary>
   <% end %>
   <% @work.title.each do |title| %>
   <atom:title type="text"><%= title %></atom:title>
   <% end %>
   <atom:updated></atom:updated>
   <sword:treatment></sword:treatment>
   <sword:verboseDescription></sword:verboseDescription>
   <sword:noOp>false</sword:noOp>
   <sword:userAgent>curl/7.51.0</sword:userAgent>
   <sword:packaging></sword:packaging>
</atom:entry>

app/views/sword/servicedocument/index.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
  <app:service xmlns:atom="http://www.w3.org/2005/Atom" xmlns:app="http://www.w3.org/2007/app" xmlns:sword="http://purl.org/net/sword/" xmlns:dcterms="http://purl.org/dc/terms/">
    <sword:version>1.3</sword:version>
    <sword:verbose>true</sword:verbose>
    <sword:noOp>true</sword:noOp>
    <sword:maxUploadSize>-1</sword:maxUploadSize>
    <atom:generator uri="http://www.dspace.org/ns/sword/1.3.1" version="1.3"/>
    <app:workspace>
    <% @admin_sets_for_user.each do |admin_set| %>
        <app:collection href="<%= deposit_url(admin_set) %>" >
          <app:accept>application/zip</app:accept>
          <sword:acceptPackaging q="1.0">http://purl.org/net/sword-types/METSDSpaceSIP</sword:acceptPackaging>
        </app:collection>
    <% end %>
    </app:workspace>
  </app:service>